name: Get from url
env:
  REPO_NAME: ${{ github.event.repository.name }}
on:
  workflow_dispatch:
    inputs:
      dl_url:
        required: true
      aria_params:
      mask_log:
        description: ''
        required: true
        default: 'true'
        type: boolean
      transcode:
        description: ''
        required: true
        default: 'false'
        type: boolean
      ffmpeg_params:
        default: "-map 0:v -map 0:a:0"
permissions:
  contents: write
jobs:
  push-script:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Mask API Key
        run: |
          echo "::add-mask::${{ secrets.TB_API_KEY }}"
      - name: Mask log
        if: ${{ github.event.inputs.mask_log == 'true' }}
        run: |
          echo "::addamask::a"
          echo "::add-mask::b"
          echo "::add-mask::c"
          echo "::add-mask::d"
          echo "::add-mask::e"
          echo "::add-mask::f"
          echo "::add-mask::g"
          echo "::add-mask::h"
          echo "::add-mask::i"
          echo "::add-mask::j"
          echo "::add-mask::k"
          echo "::add-mask::l"
          echo "::add-mask::m"
          echo "::add-mask::n"
          echo "::add-mask::o"
          echo "::add-mask::p"
          echo "::add-mask::q"
          echo "::add-mask::r"
          echo "::add-mask::s"
          echo "::add-mask::t"
          echo "::add-mask::u"
          echo "::add-mask::v"
          echo "::add-mask::w"
          echo "::add-mask::x"
          echo "::add-mask::y"
          echo "::add-mask::z"
          echo "::add-mask::1"
          echo "::add-mask::2"
          echo "::add-mask::3"
          echo "::add-mask::4"
          echo "::add-mask::5"
          echo "::add-mask::6"
          echo "::add-mask::7"
          echo "::add-mask::8"
          echo "::add-mask::9"
          echo "::add-mask::0"
      - name: Masking inputs
        run: |
          DOWNLOAD_URL=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.dl_url' )
          echo "::add-mask::$DOWNLOAD_URL"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup
        if: ${{ !github.event.repository.is_template }}
        run: |
          aria2c -x 16 "https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-07-11-14-04/ffmpeg-N-120228-g3334bdc6e7-linux64-gpl.tar.xz"
          tar -xvf ffmpeg-N-120228-g3334bdc6e7-linux64-gpl.tar.xz
          sudo mv ffmpeg-N-120228-g3334bdc6e7-linux64-gpl/bin/* /usr/local/bin
          rm -rf ffmpeg-N-120228-g3334bdc6e7-linux64-gpl.tar.xz
          sudo rm -rf ffmpeg-N-120228-g3334bdc6e7-linux64-gpl
          wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
          chmod +x yt-dlp
          sudo mv yt-dlp /usr/local/bin
          sudo chmod +x /usr/local/bin/yt-dlp
      - name: Setup git
        if: ${{ !github.event.repository.is_template }}
        run: |
          git config --global core.compression 1
          git config --global http.postBuffer 524288000
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Cleanup
        if: ${{ !github.event.repository.is_template }}
        run: |
          mv .github ..
          rm -rf *
          mv ../.github .
          git add . || true
          git commit -m m || true
          git push -f || true
      - name: Make changes and push
        if: ${{ !github.event.repository.is_template }}
        run: |
          aria2c ${{github.event.inputs.aria_params}} -x 16 "${{ github.event.inputs.dl_url }}" --summary-interval=1 -o video
          if [[ ${{ github.event.inputs.transcode}} == "true" ]]; then
            echo "Transcoding"
            ffmpeg \
            -i video ${{github.event.inputs.ffmpeg_params}} \
            -c:v libx264 -preset ultrafast -c:a aac \
            -hls_time 10 -hls_list_size 0 -f hls index.m3u8
          else
            ffmpeg \
            -i video -map 0 -map -0:s -c copy -start_number 0 \
            -hls_time 6 -hls_list_size 0 -f hls index.m3u8
          fi
          
          rm -rf video
          
          git add index20* 2>/dev/null; git commit -m a; git push
          git add index19* 2>/dev/null; git commit -m a; git push
          git add index18* 2>/dev/null; git commit -m a; git push
          git add index17* 2>/dev/null; git commit -m a; git push
          git add index16* 2>/dev/null; git commit -m a; git push
          git add index15* 2>/dev/null; git commit -m a; git push
          git add index14* 2>/dev/null; git commit -m a; git push
          git add index13* 2>/dev/null; git commit -m a; git push
          git add index12* 2>/dev/null; git commit -m a; git push
          git add index11* 2>/dev/null; git commit -m a; git push
          git add index10* 2>/dev/null; git commit -m a; git push
          git add index9* 2>/dev/null; git commit -m a; git push
          git add index8* 2>/dev/null; git commit -m a; git push
          git add index7* 2>/dev/null; git commit -m a; git push
          git add index6* 2>/dev/null; git commit -m a; git push
          git add index5* 2>/dev/null; git commit -m a; git push
          git add index4* 2>/dev/null; git commit -m a; git push
          git add index3* 2>/dev/null; git commit -m a; git push
          git add index2* 2>/dev/null; git commit -m a; git push
          git add index1* 2>/dev/null; git commit -m a; git push
          git add . || true
          git commit -m m || true
          git push || true
      - name: Epilogue
        run: |
          export ID=$(echo "$REPO_NAME" | sed 's/-/:/g')
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gconsole00/${{github.event.repository.name}}/actions/permissions \
          -d '{"enabled":false}'
          
      - name: Send telegram
        if: failure()
        run: |
          curl "https://api.telegram.org/${{secrets.TG_BOTID_TOKEN}}/sendMessage?chat_id=${{secrets.TG_CHAT_ID}}&text=URL_Action_Failed_For%20https://github.com/gconsole00/$REPO_NAME/actions"
